-- Fichier dropTables.sql
DROP TABLE IF EXISTS DELIVERY_INCIDENTS;
DROP TABLE IF EXISTS DELIVERY_STATUS_HISTORY;
DROP TABLE IF EXISTS ROUTE_STOPS;
DROP TABLE IF EXISTS DELIVERIES;
DROP TABLE IF EXISTS DELIVERY_ROUTES;
DROP TABLE IF EXISTS VEHICLE_ASSIGNMENTS;
DROP TABLE IF EXISTS VEHICLES;
DROP TABLE IF EXISTS DELIVERY_RATES;
DROP TABLE IF EXISTS DELIVERY_ZONES;
DROP TABLE IF EXISTS DEPOTS;