-- Fichier selectAll.sql
SELECT * FROM DEPOTS;
SELECT * FROM DELIVERY_ZONES;
SELECT * FROM DELIVERY_RATES;
SELECT * FROM VEHICLES;
SELECT * FROM VEHICLE_ASSIGNMENTS;
SELECT * FROM DELIVERY_ROUTES;
SELECT * FROM DELIVERIES;
SELECT * FROM ROUTE_STOPS;
SELECT * FROM DELIVERY_STATUS_HISTORY;
SELECT * FROM DELIVERY_INCIDENTS;